name = "Cyclic_Antimicrobial_Peptide_Design"
description="A DPO-aligned discovery pipeline for selective cyclic antmicrobial peptides."

[dependencies]
# Node 02 (folding) requires output from Node 01 (ingestion)
02-structure-prediction = ["01-sequence-ingest"]

# Node 03 (membrane scoring) requires output from Node 02 (structure prediction)
03-membrane-scoring = ["02-structure-prediction"]

# Node 04 (dpo iteration) requires output from Node 03 (membrane scoring)
04-dpo-iteration = ["03-membrane-scoring"]

# Node 05 (structure & scoring generation) requires output from Node 04 (dpo iteration) 
05-structure-scoring-generated = ["04-dpo-iteration"]

# Node 06 (physics validation) required output from Node 05 (structure scoring generation)
06-physics-validation = ["05-structure-scoring-generated"]