name = "Sequence Ingest"
description = "Ingest sequence data into the database"
inputs = ["sequences.csv"]
outputs = ["output_files/ingested_sequences.csv"]


[container]
image = "sequence-ingest:latest"

[scripts]
run = "run.sh"

[params.data_paths]
type = "string"
default = '{"input":"sequences.csv", "output":"output_files/ingested_sequences.csv"}'
hint = "JSON string containing input and output file paths"